<?php


function your_module_get_user_timezone() {
  global $user;
  if (variable_get('configurable_timezones', 1) && $user->uid && $user->timezone) {
    return $user->timezone;
  }
  else {
    // Ignore PHP strict notice if time zone has not yet been set in the php.ini
    // configuration.
    return variable_get('date_default_timezone', @date_default_timezone_get());
  }
}

/**
 * Implementation of hook_block()
 */
function your_module_block($op='list', $delta=0, $edit=array()) {
 switch ($op) {
 case 'list':
 $blocks[0]['info'] = t(’Timezone');
 return $blocks;
 case 'view':
 $blocks['subject'] = t(‘Timezone Display');
 $blocks[’get_user_timezone'] = t('Your timezone is');
 return $blocks;
 }
}
}